### ISSUE TITLE
Get assessments method doesn't do what it claims

### ISSUE THREAD

**Issue by halfcaffzach** [AssessmentHQ/assessment-tracker#60]
The endpoint itself is /assessments/id but the id is never used. The comments claim that it is attempting to get all assessments for a trainee but it is not doing that and is instead loading every assessment contained in the db.

If it is trying to get all assessments for a trainee, wouldn't we want/need their grade for the assessment if they have completed it?

**Comment by Seri96** [comment]
fixed
