### ISSUE TITLE
Create assessment fails

### ISSUE THREAD

**Issue by halfcaffzach** [AssessmentHQ/assessment-tracker#63]
PSQLException: ERROR: zero-length delimited identifier at or near """"

**Comment by halfcaffzach** [comment]
There are also a lot of 0s being added in place of things that should have value

**Comment by halfcaffzach** [comment]
Assessment succeeds but needs more info

**Comment by JGay90** [comment]
Has been updated to take in object and updated the default values to be 1s so it won't break the SQL. Did update dao to take in obj and added more wildcard values to be pulled from obj
